# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Officially Awesome
email: officials@londonrollerderby.com
description: >- # this means to ignore newlines until "url:"
  Resources for awesome roller derby officials.

url: "https://officiallyawesome.uk"
baseurl: ""
locale: "en-GB"
repository: officiallyawesome/officiallyawesome

# twitter_username: officiallyawesome
github_username: officiallyawesome
# minimal_mistakes_skin: air
minimal_mistakes_skin: dark
logo: "/assets/images/lrd-logo-sml-onblack.png"
search: false
breadcrumbs: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - submodules
  - _resources/magnet-board/theming.md
  - _resources/magnet-board/roadmap.txt
  - _resources/magnet-board/privacy_policy.txt

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme

remote_theme: "mmistakes/minimal-mistakes@4.19.2"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/officially-awesome/officiallyawesome"
    # - label: "Categories"
    #   icon: "fa fa-fw fa-cat"
    #   url: /categories/
    # - label: "Tags"
    #   icon: "fa fa-fw fa-tags"
    #   url: /tags/

collections:
  referee-school:
    output: true
    permalink: /:collection/:path/
  resources:
    output: true
    permalink: /:collection/:path/

defaults:
  # _referee-school
  - scope:
      path: ""
      type: referee-school
    values:
      layout: single
      excerpt_separator: "<!-- more -->"
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
      paginate: true
  # _resources
  - scope:
      path: ""
      type: resources
    values:
      layout: single
      excerpt_separator: "<!-- more -->"
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
      paginate: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      related: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
